spring:
  application:
    name: gran-mente

  datasource:
     url: jdbc:postgresql://localhost:5432/granmente_db
     driver-class-name: org.postgresql.Driver
     username: postgres
     password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true
        use_sql_comments: true

  thymeleaf:
    cache: false

server:
  port: 8080
  servlet:
    session:
      timeout: 30m

app:
  seed:
    enabled: true
  ai:
    fallback-enabled: true
    gemini:
      api-key: ${GCP_API_KEY}
      model: gemini-2.5-flash

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    pe.edu.utp.granmente: INFO    